global Consts {
    out property <length> width: 320px;
    out property <length> height: 240px;
    out property<color> case-color: white;
    out property<color> button-color: blue;
    out property <color> bg-color: black;
}

component Button inherits Rectangle {
    width: 40px;
    height: 20px;
    border-radius: 5px;
    border-color: white;
    border-width: 1px;
    background: Consts.button-color;
}

component Stick {
    in property <int> dx: 0;
    in property <int> dy: 0;
    in property <bool> clicked: false;

    Rectangle {
        x: dx * 5px - self.width / 2;
        y: dy * 5px - self.height / 2;
        width: clicked ? 30px : 40px;
        height: self.width;
        border-radius: self.width / 2;
        background: Consts.button-color;
        drop-shadow-offset-x: clicked ? 1px : 2px;
        drop-shadow-offset-y: clicked ? 1px : 2px;
        drop-shadow-color: black;
        drop-shadow-blur: clicked ? 2px : 4px;
    }
}

component Led inherits Rectangle {
    in property <bool> on: false;
    visible: on;
    x: 180px;
    y: 210px;
    width: 20px;
    height: 20px;
    border-radius: 10px;
    border-color: self.background.mix(white, 0.25);
    border-width: 3px;
    background: blue;
}

component WioImage inherits Image {
    width: 86px;
    height: 64px;
}

component WioTerminal {
    width: Consts.width;
    height: Consts.height;
    in property <color> text-color: lime;
    in property <image> image: @image-url("ferris.png");
    in-out property<bool> is-button1-pressed;
    in-out property<bool> is-button2-pressed;
    in-out property<bool> is-button3-pressed;
    in-out property<bool> is-left-pressed;
    in-out property<bool> is-up-pressed;
    in-out property<bool> is-right-pressed;
    in-out property<bool> is-down-pressed;
    in-out property<bool> is-return-pressed;
    in property <bool> led-on;

    Button {
        x: 40px;
        y: is-button1-pressed ? 15px : 10px;
    }
    Button {
        x: 90px;
        y: is-button2-pressed ? 15px : 10px;
    }
    Button {
        x: 140px;
        y: is-button3-pressed ? 15px : 10px;
    }

    base := Rectangle { 
        x: 20px;
        y: 20px;
        width: 280px;
        height: 200px;
        background: Consts.case-color;
        border-radius: 10px;
        drop-shadow-offset-x: 5px;
        drop-shadow-offset-y: 5px;
        drop-shadow-color: gray;
        drop-shadow-blur: 10px;
    }
    Led { x: 120px; background: lime; on: true; }
    led := Led { on: root.led-on; }
    lcd := Rectangle {
        x: 25px;
        y: 25px;
        width: 270px;
        height: 170px;
        border-radius: 8px;
        background: Consts.bg-color;
        WioImage {
            source: root.image;
        }    
    }

    Stick {
        x: 260px;
        y: 190px;
        dx: is-left-pressed ? -1 : is-right-pressed ? 1 : 0;
        dy: is-up-pressed ? -1 : is-down-pressed ? 1 : 0;
        clicked: is-return-pressed;
    }

    // Buzzer
    for i[index] in [0, 1, 2, 3] : Rectangle {
        Rectangle {
            x:45px + i * 10px;
            y: 200px;
            width: 5px;
            height: 15px;
            border-radius: 2px;
            background: gray;
        }
    }

    Text {
        x: 60px;
        y: 40px;
        text: "Booting Wio Terminal...";
        font-size: 16px;
        color: root.text-color;
    }
}

export component MainWindow inherits Window {
    width: Consts.width;
    height: Consts.height;
    background: black;
    default-font-family: "Noto Sans";
    in property <bool> led-on <=> wio_terminal.led-on;

    wio_terminal := WioTerminal {}

    forward-focus: my-key-handler;
    my-key-handler := FocusScope {
        key-pressed(event) => {
            debug(event.text);
            if (event.text == Key.F1) {
                wio_terminal.is-button1-pressed = true;
            }
            if (event.text == Key.F2) {
                wio_terminal.is-button2-pressed = true;
            }
            if (event.text == Key.F3) {
                wio_terminal.is-button3-pressed = true;
            }
            if (event.text == Key.LeftArrow) {
                wio_terminal.is-left-pressed = true;
            }
            if (event.text == Key.RightArrow) {
                wio_terminal.is-right-pressed = true;
            }
            if (event.text == Key.UpArrow) {
                wio_terminal.is-up-pressed = true;
            }
            if (event.text == Key.DownArrow) {
                wio_terminal.is-down-pressed = true;
            }
            if (event.text == Key.Return) {
                wio_terminal.is-return-pressed = true;
            }
            accept
        }
        key-released(event) => {
            debug(event.text);
            if (event.text == Key.F1) {
                wio_terminal.is-button1-pressed = false;
            }
            if (event.text == Key.F2) {
                wio_terminal.is-button2-pressed = false;
            }
            if (event.text == Key.F3) {
                wio_terminal.is-button3-pressed = false;
            }
            if (event.text == Key.LeftArrow) {
                wio_terminal.is-left-pressed = false;
            }
            if (event.text == Key.RightArrow) {
                wio_terminal.is-right-pressed = false;
            }
            if (event.text == Key.UpArrow) {
                wio_terminal.is-up-pressed = false;
            }
            if (event.text == Key.DownArrow) {
                wio_terminal.is-down-pressed = false;
            }
            if (event.text == Key.Return) {
                wio_terminal.is-return-pressed = false;
            }
            accept
        }
    }
}